name = "auto-battle-counter-sync"
main = "index.js"
compatibility_date = "2026-10-05"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "https://lucienwooo.github.io"

[[kv_namespaces]]
binding = "AUTO_BATTLE_DATA"
id = "7353daa2c5a34c34816f5fad1db0348d"

[[ratelimits]]
name = "LOGIN_RATE_LIMITER"
namespace_id = "472951"

	[ratelimits.simple]
	limit = 20
	period = 60
